//! Unified narrowphase contact generation for all dynamic-vs-dynamic collider pairs.

use std::collections::{HashMap, HashSet};

use generational_arena::Arena;
use nalgebra::{Point3, UnitQuaternion, Vector3};

use crate::collision::contact::ContactManifold;
use crate::collision::continuous::swept_sphere_sphere;
use crate::collision::discrete::obb_obb::obb_obb_manifold_cached;
use crate::collision::discrete::sphere_obb::sphere_obb_manifold;
use crate::collision::discrete::sphere_sphere::sphere_sphere_manifold;
use crate::collision::obb::Obb;
use crate::collision::sat::SatCache;
use crate::physics::body::RigidBody;
use crate::physics::collider::{Collider, ColliderMaterial, ColliderShape};
use crate::physics::handle::{ColliderHandle, RigidBodyHandle};
use crate::physics::pipeline::solver::ContactConstraint;

/// Pair key for SAT axis caching. Collider handles are stored in canonical order.
#[derive(Hash, Eq, PartialEq, Clone, Copy)]
struct SatPairKey(ColliderHandle, ColliderHandle);

impl SatPairKey {
    fn new(a: ColliderHandle, b: ColliderHandle) -> Self {
        let (idx_a, _) = a.raw_parts();
        let (idx_b, _) = b.raw_parts();
        if idx_a <= idx_b {
            Self(a, b)
        } else {
            Self(b, a)
        }
    }
}

/// Per-frame SAT axis cache for OBB-OBB pairs.
///
/// Stores the last separating axis found for each pair. When the cached axis
/// still separates the pair next frame, the full 15-axis SAT test is skipped.
pub struct SatCacheMap {
    caches: HashMap<SatPairKey, SatCache>,
}

impl SatCacheMap {
    pub fn new() -> Self {
        Self {
            caches: HashMap::new(),
        }
    }

    /// Remove entries for pairs that were not tested this frame.
    pub fn prune(&mut self, active_pairs: &HashSet<(ColliderHandle, ColliderHandle)>) {
        self.caches.retain(|key, _| {
            active_pairs.contains(&(key.0, key.1)) || active_pairs.contains(&(key.1, key.0))
        });
    }
}

/// Shape-agnostic snapshot of a collider's world-space state for pair dispatch.
struct ColliderState {
    body_handle: RigidBodyHandle,
    collider_handle: ColliderHandle,
    center: Point3<f32>,
    rotation: UnitQuaternion<f32>,
    shape: ColliderShape,
    bounding_radius: f32,
    velocity: Vector3<f32>,
    material: ColliderMaterial,
    is_sleeping: bool,
}

/// Reusable work buffer for the dynamic narrowphase pipeline.
///
/// All internal `Vec`s are cleared (but not deallocated) each frame, eliminating
/// per-frame heap allocations in the narrowphase hot path. The buffer should be
/// created once and reused across frames via [`generate_dynamic_contacts`].
pub struct NarrowphaseWorkBuffer {
    states: Vec<ColliderState>,
    bounds: Vec<([f32; 3], [f32; 3])>,
    sorted_indices: Vec<usize>,
    pairs: Vec<(usize, usize)>,
    contacts: Vec<ContactConstraint>,
    active_box_pairs: HashSet<(ColliderHandle, ColliderHandle)>,
}

impl NarrowphaseWorkBuffer {
    pub fn new() -> Self {
        Self {
            states: Vec::new(),
            bounds: Vec::new(),
            sorted_indices: Vec::new(),
            pairs: Vec::new(),
            contacts: Vec::new(),
            active_box_pairs: HashSet::new(),
        }
    }

    fn clear(&mut self) {
        self.states.clear();
        self.bounds.clear();
        self.sorted_indices.clear();
        self.pairs.clear();
        self.contacts.clear();
        self.active_box_pairs.clear();
    }

    /// Read the contacts generated by the last call to [`generate_dynamic_contacts`].
    pub fn contacts(&self) -> &[ContactConstraint] {
        &self.contacts
    }
}

/// Generate contacts between all pairs of non-static colliders.
///
/// Uses sort-and-sweep broadphase on the axis of greatest positional spread
/// to prune pairs before narrowphase dispatch. Results are written into
/// `buf.contacts` and can be read via [`NarrowphaseWorkBuffer::contacts`].
///
/// The work buffer's internal `Vec`s are reused across frames — only cleared,
/// never deallocated — eliminating per-frame allocation overhead.
pub fn generate_dynamic_contacts(
    bodies: &Arena<RigidBody>,
    colliders: &Arena<Collider>,
    contact_margin: f32,
    dt: f32,
    ccd_threshold: f32,
    enable_speculative_contacts: bool,
    speculative_min_speed: f32,
    speculative_margin_multiplier: f32,
    sleeping: Option<&HashSet<RigidBodyHandle>>,
    sat_cache_map: &mut SatCacheMap,
    buf: &mut NarrowphaseWorkBuffer,
) {
    buf.clear();

    collect_collider_states_into(&mut buf.states, bodies, colliders, sleeping);
    if buf.states.len() < 2 {
        return;
    }

    sweep_and_prune_into(
        &buf.states,
        contact_margin,
        &mut buf.bounds,
        &mut buf.sorted_indices,
        &mut buf.pairs,
    );

    // Snapshot pairs so we can iterate while mutating buf.contacts.
    // pairs is already populated by sweep_and_prune_into; iterate by index.
    for pair_idx in 0..buf.pairs.len() {
        let (i, j) = buf.pairs[pair_idx];
        let si = &buf.states[i];
        let sj = &buf.states[j];

        match (&si.shape, &sj.shape) {
            (ColliderShape::Sphere { radius: ra }, ColliderShape::Sphere { radius: rb }) => {
                sphere_sphere_pair(
                    si,
                    *ra,
                    sj,
                    *rb,
                    contact_margin,
                    dt,
                    ccd_threshold,
                    enable_speculative_contacts,
                    speculative_min_speed,
                    speculative_margin_multiplier,
                    &mut buf.contacts,
                );
            }
            (ColliderShape::Sphere { radius }, ColliderShape::Box { half_extents }) => {
                sphere_box_pair(si, *radius, sj, *half_extents, contact_margin, &mut buf.contacts);
            }
            (ColliderShape::Box { half_extents }, ColliderShape::Sphere { radius }) => {
                box_sphere_pair(si, *half_extents, sj, *radius, contact_margin, &mut buf.contacts);
            }
            (
                ColliderShape::Box { half_extents: he_a },
                ColliderShape::Box { half_extents: he_b },
            ) => {
                buf.active_box_pairs
                    .insert((si.collider_handle, sj.collider_handle));
                box_box_pair(
                    si,
                    *he_a,
                    sj,
                    *he_b,
                    contact_margin,
                    sat_cache_map,
                    &mut buf.contacts,
                );
            }
        }
    }

    sat_cache_map.prune(&buf.active_box_pairs);
}

/// Sort-and-sweep broadphase, writing candidate pairs into pre-allocated buffers.
fn sweep_and_prune_into(
    states: &[ColliderState],
    margin: f32,
    bounds: &mut Vec<([f32; 3], [f32; 3])>,
    sorted: &mut Vec<usize>,
    pairs: &mut Vec<(usize, usize)>,
) {
    let sweep_axis = pick_sweep_axis(states);

    // Build (aabb_min, aabb_max) per collider on each axis.
    bounds.reserve(states.len().saturating_sub(bounds.capacity()));
    for s in states {
        let r = s.bounding_radius + margin;
        bounds.push((
            [s.center.x - r, s.center.y - r, s.center.z - r],
            [s.center.x + r, s.center.y + r, s.center.z + r],
        ));
    }

    // Sort indices by AABB min on the sweep axis.
    sorted.extend(0..states.len());
    sorted.sort_unstable_by(|&a, &b| {
        bounds[a].0[sweep_axis]
            .partial_cmp(&bounds[b].0[sweep_axis])
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    for ii in 0..sorted.len() {
        let i = sorted[ii];
        let i_max = bounds[i].1[sweep_axis];

        for jj in (ii + 1)..sorted.len() {
            let j = sorted[jj];

            if bounds[j].0[sweep_axis] > i_max {
                break;
            }

            if states[i].is_sleeping && states[j].is_sleeping {
                continue;
            }

            if aabb_overlap_3d(&bounds[i], &bounds[j]) {
                pairs.push((i, j));
            }
        }
    }
}

/// Pick the axis (0=x, 1=y, 2=z) with the greatest positional spread.
fn pick_sweep_axis(states: &[ColliderState]) -> usize {
    let mut min = [f32::MAX; 3];
    let mut max = [f32::MIN; 3];
    for s in states {
        let c = [s.center.x, s.center.y, s.center.z];
        for axis in 0..3 {
            min[axis] = min[axis].min(c[axis]);
            max[axis] = max[axis].max(c[axis]);
        }
    }
    let spread = [max[0] - min[0], max[1] - min[1], max[2] - min[2]];
    if spread[0] >= spread[1] && spread[0] >= spread[2] {
        0
    } else if spread[1] >= spread[2] {
        1
    } else {
        2
    }
}

/// Full 3-axis AABB overlap test.
fn aabb_overlap_3d(a: &([f32; 3], [f32; 3]), b: &([f32; 3], [f32; 3])) -> bool {
    a.0[0] <= b.1[0]
        && a.1[0] >= b.0[0]
        && a.0[1] <= b.1[1]
        && a.1[1] >= b.0[1]
        && a.0[2] <= b.1[2]
        && a.1[2] >= b.0[2]
}

fn collect_collider_states_into(
    states: &mut Vec<ColliderState>,
    bodies: &Arena<RigidBody>,
    colliders: &Arena<Collider>,
    sleeping: Option<&HashSet<RigidBodyHandle>>,
) {
    for (idx, body) in bodies.iter() {
        if body.is_static() {
            continue;
        }
        let body_handle = RigidBodyHandle(idx);
        let is_sleeping = sleeping
            .map(|s| s.contains(&body_handle))
            .unwrap_or(false);

        for collider_handle in body.colliders() {
            let Some(collider) = colliders.get(collider_handle.0) else {
                continue;
            };
            states.push(ColliderState {
                body_handle,
                collider_handle: *collider_handle,
                center: collider.world_center(body.position(), body.rotation()),
                rotation: body.rotation(),
                shape: collider.shape().clone(),
                bounding_radius: collider.shape().bounding_radius(),
                velocity: body.linear_velocity(),
                material: *collider.material(),
                is_sleeping,
            });
        }
    }
}

fn sphere_sphere_pair(
    a: &ColliderState,
    radius_a: f32,
    b: &ColliderState,
    radius_b: f32,
    contact_margin: f32,
    dt: f32,
    ccd_threshold: f32,
    enable_speculative_contacts: bool,
    speculative_min_speed: f32,
    speculative_margin_multiplier: f32,
    out: &mut Vec<ContactConstraint>,
) {
    let manifold = sphere_sphere_manifold(a.center, radius_a, b.center, radius_b, contact_margin);

    if !manifold.is_empty() {
        push_manifold_constraints(
            out,
            &manifold,
            Some(a.body_handle),
            b.body_handle,
            Some(a.collider_handle),
            Some(b.collider_handle),
            &a.material,
            &b.material,
        );
        return;
    }

    // Speculative CCD.
    if should_add_speculative(
        a.velocity.magnitude() * dt,
        radius_a,
        b.velocity.magnitude() * dt,
        radius_b,
        ccd_threshold,
        contact_margin,
        enable_speculative_contacts,
        speculative_min_speed,
        speculative_margin_multiplier,
    ) {
        let end_a = a.center + a.velocity * dt;
        let end_b = b.center + b.velocity * dt;
        if let Some(t) = swept_sphere_sphere(
            a.center,
            end_a,
            radius_a + contact_margin,
            b.center,
            end_b,
            radius_b + contact_margin,
        ) {
            let pos_a = a.center + (end_a - a.center) * t;
            let pos_b = b.center + (end_b - b.center) * t;
            let delta = pos_b - pos_a;
            let dist = delta.magnitude();
            let normal = if dist < 1e-6 {
                Vector3::y()
            } else {
                delta / dist
            };
            let actual_depth = (radius_a + radius_b) - dist;
            let solver_depth = actual_depth.max(0.0);
            let point = pos_a + normal * (radius_a - actual_depth * 0.5);
            let (restitution, friction) = ColliderMaterial::combine(&a.material, &b.material);
            out.push(ContactConstraint {
                body_a: Some(a.body_handle),
                body_b: b.body_handle,
                collider_a: Some(a.collider_handle),
                collider_b: Some(b.collider_handle),
                point,
                normal,
                raw_normal: normal,
                depth: solver_depth,
                raw_depth: actual_depth,
                restitution,
                friction,
                warm_normal_impulse: 0.0,
                warm_tangent_impulse: [0.0, 0.0],
            });
        }
    }
}

fn sphere_box_pair(
    sphere: &ColliderState,
    radius: f32,
    box_state: &ColliderState,
    half_extents: Vector3<f32>,
    contact_margin: f32,
    out: &mut Vec<ContactConstraint>,
) {
    let obb = Obb::new(box_state.center, box_state.rotation, half_extents);
    let manifold = sphere_obb_manifold(&obb, sphere.center, radius, contact_margin);
    push_manifold_constraints(
        out,
        &manifold,
        Some(box_state.body_handle),
        sphere.body_handle,
        Some(box_state.collider_handle),
        Some(sphere.collider_handle),
        &box_state.material,
        &sphere.material,
    );
}

fn box_sphere_pair(
    box_state: &ColliderState,
    half_extents: Vector3<f32>,
    sphere: &ColliderState,
    radius: f32,
    contact_margin: f32,
    out: &mut Vec<ContactConstraint>,
) {
    sphere_box_pair(sphere, radius, box_state, half_extents, contact_margin, out);
}

fn box_box_pair(
    a: &ColliderState,
    he_a: Vector3<f32>,
    b: &ColliderState,
    he_b: Vector3<f32>,
    contact_margin: f32,
    sat_cache_map: &mut SatCacheMap,
    out: &mut Vec<ContactConstraint>,
) {
    let obb_a = Obb::new(a.center, a.rotation, he_a);
    let obb_b = Obb::new(b.center, b.rotation, he_b);
    let key = SatPairKey::new(a.collider_handle, b.collider_handle);
    let cache = sat_cache_map.caches.entry(key).or_default();
    let manifold = obb_obb_manifold_cached(&obb_a, &obb_b, contact_margin, cache);
    push_manifold_constraints(
        out,
        &manifold,
        Some(a.body_handle),
        b.body_handle,
        Some(a.collider_handle),
        Some(b.collider_handle),
        &a.material,
        &b.material,
    );
}

/// Append contact constraints from a collision manifold directly into the output buffer.
fn push_manifold_constraints(
    out: &mut Vec<ContactConstraint>,
    manifold: &ContactManifold,
    body_a: Option<RigidBodyHandle>,
    body_b: RigidBodyHandle,
    collider_a: Option<ColliderHandle>,
    collider_b: Option<ColliderHandle>,
    material_a: &ColliderMaterial,
    material_b: &ColliderMaterial,
) {
    if manifold.is_empty() {
        return;
    }
    let (restitution, friction) = ColliderMaterial::combine(material_a, material_b);
    for cp in &manifold.points {
        out.push(ContactConstraint {
            body_a,
            body_b,
            collider_a,
            collider_b,
            point: cp.point,
            normal: cp.normal,
            raw_normal: cp.raw_normal,
            depth: cp.depth,
            raw_depth: cp.raw_depth,
            restitution,
            friction,
            warm_normal_impulse: 0.0,
            warm_tangent_impulse: [0.0, 0.0],
        });
    }
}

fn should_add_speculative(
    travel_a: f32,
    radius_a: f32,
    travel_b: f32,
    radius_b: f32,
    ccd_threshold: f32,
    contact_margin: f32,
    enable_speculative_contacts: bool,
    speculative_min_speed: f32,
    speculative_margin_multiplier: f32,
) -> bool {
    if !enable_speculative_contacts {
        return false;
    }
    let margin_gate = contact_margin * speculative_margin_multiplier;
    let fast_a = travel_a >= speculative_min_speed
        && travel_a > margin_gate
        && travel_a <= radius_a * ccd_threshold;
    let fast_b = travel_b >= speculative_min_speed
        && travel_b > margin_gate
        && travel_b <= radius_b * ccd_threshold;
    fast_a || fast_b
}
